rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - rbx-2
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
script: "bundle exec rake"
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/5.0.gemfile
    - rvm: 1.9
      gemfile: gemfiles/5.1.gemfile
    - rvm: 1.9
      gemfile: gemfiles/5.2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/5.1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/5.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.5
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.5
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.5
      gemfile: gemfiles/4.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/3.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/4.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/4.1.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
branches:
  only:
    - master

sudo: false
cache: bundler
